#!/bin/csh -v

# We're using this to get rid of files generated by
# Visual Studio. Most likely you won't need this script.

pushd $ldpk/windows
sudo rm -rf LD_3DE4_NukeMultiRelease/.vs
sudo rm -rf LD_3DE4_NukeMultiRelease/LD_3DE4_NukeMultiRelease_VS2015*db
sudo rm -rf LD_3DE4_NukeMultiRelease/x64
sudo rm -rf LD_3DE4_NukeMultiRelease/*/x64
sudo rm -rf LD_3DE4_NukeMultiRelease/*/*.vcxproj.user
sudo rm -rf LD_3DE4_NukeMultiRelease/Debug
sudo rm -rf LD_3DE4_NukeMultiRelease/*/Debug
popd
